In [1]:
print("hello world")

hello world


In [1]:
import numpy as np

In [2]:
mlist = [1,2,3]

In [3]:
type(mlist)

list

In [4]:
myarray = np.array(mlist)

In [5]:
myarray

array([1, 2, 3])

In [8]:
type(myarray)

numpy.ndarray

In [11]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [14]:
np.zeros(shape=(10,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones(shape=(1,5))

array([[1., 1., 1., 1., 1.]])

In [17]:
np.random.seed(101)
arr = np.random.randint(0, 100, 10)

In [18]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [19]:
arr2 = np.random.randint(0, 100,10)

In [20]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [21]:
arr.max()

95

In [22]:
arr.argmax()

0

In [23]:
arr.min()

9

In [24]:
arr.argmin()

7

In [25]:
arr.mean()

60.8

In [30]:
arr.reshape((5,2))

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])

In [52]:
myarray.reshape(3,1)

array([[1],
       [2],
       [3]])

In [62]:
mat = np.arange(0,100).reshape(10,10)

In [63]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [64]:
row = 7
col = 6

In [65]:
mat[row, col]

76

In [66]:
mat[:,1].reshape(10,1)

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [67]:
mat[1,:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [68]:
mat[0:3, 1:4]

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23]])

In [69]:
mat[0:3, :] = 999

In [70]:
mat

array([[999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])